version: '2'
services:
    jhipsterregistry-app:
        image: jhipsterregistry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
